remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-remote-theme

color_scheme: dark

logo: "/assets/logo_transparent.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.8.0"

nav_external_links:
  - title: ServiceAuthCentral on GitHub
    url: https://github.com/UnitVectorY-Labs/ServiceAuthCentral

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/ServiceAuthCentral"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
