name: Build and Push Development Docker Images

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: docker-${{ matrix.profile }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - profile: server-manage
            tag: manage
          - profile: server-token
            tag: token

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository name
      run: |
        echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ env.REPO_LC }}-${{ matrix.tag }}-snapshot:dev
        build-args: |
          MAVEN_PROFILE=${{ matrix.profile }}

    - name: Set lowercase package name
      run: |
        PACKAGE_NAME=${GITHUB_REPOSITORY##*/}
        echo "PACKAGE_NAME_LC=${PACKAGE_NAME,,}" >> $GITHUB_ENV

    - name: Clean up untagged (dangling) docker images
      uses: actions/delete-package-versions@v5
      with:
        owner: ${{ github.repository_owner }}
        package-name: ${{ env.PACKAGE_NAME_LC }}-${{ matrix.tag }}-snapshot
        package-type: container
        min-versions-to-keep: 1-
        delete-only-untagged-versions: 'true'
